// GERMAN250 - 250 pantallas
// Compatible con index_GERMAN250.html
const phrases = [
  { english: "eins · zwei · drei · vier", pronunciation: "ains · tsvai · drai · fiar", spanish: "uno · dos · tres · cuatro" },
  { english: "fünf · sechs · sieben · acht", pronunciation: "fünf · zeks · zí-ben · ajt", spanish: "cinco · seis · siete · ocho" },
  { english: "neun · zehn · elf · zwölf", pronunciation: "noin · tsein · elf · tsvölf", spanish: "nueve · diez · once · doce" },
  { english: "dreizehn · vierzehn · fünfzehn · sechzehn", pronunciation: "drai-tsein · fíar-tsein · fünft-sein · zeks-tsein", spanish: "trece · catorce · quince · dieciséis" },
  { english: "siebzehn · achtzehn · neunzehn · zwanzig", pronunciation: "zíip-tsein · ajt-tsein · noin-tsein · tsván-tsig", spanish: "diecisiete · dieciocho · diecinueve · veinte" },
  { english: "dreißig · vierzig · fünfzig · sechzig", pronunciation: "drai-sig · fíar-tsig · fünft-sig · zeks-tsig", spanish: "treinta · cuarenta · cincuenta · sesenta" },
  { english: "siebzig · achtzig · neunzig · hundert", pronunciation: "zíip-tsig · ajt-tsig · noin-tsig · hún-dert", spanish: "setenta · ochenta · noventa · cien" },
  { english: "zweihundert · dreihundert · vierhundert · fünfhundert", pronunciation: "tsvai-hún-dert · drai-hún-dert · fíar-hún-dert · fünft-hún-dert", spanish: "doscientos · trescientos · cuatrocientos · quinientos" },
  { english: "tausend · zweitausend · dreitausend · zehntausend", pronunciation: "táu-send · tsvai-táu-send · drai-táu-send · tsein-táu-send", spanish: "mil · dos mil · tres mil · diez mil" },
  { english: "hunderttausend · eine Million · halb · doppelt", pronunciation: "hún-dert-táu-send · ái-ne mili-ón · halp · dóp-pelt", spanish: "cien mil · un millón · medio · doble" },
  { english: "Hallo · Guten Morgen · Guten Tag", pronunciation: "já-lo · gú-ten mór-guen · gú-ten tak", spanish: "hola · buenos días · buenas tardes" },
  { english: "Gute Nacht · Auf Wiedersehen · Bis später · Bis morgen", pronunciation: "gú-te najt · auf ví-der-ze-en · bis shpé-ter · bis mór-guen", spanish: "buenas noches · adiós · hasta luego · hasta mañana" },
  { english: "Bis bald · Danke · Bitte", pronunciation: "bis balt · dán-ke · bí-te", spanish: "hasta pronto · gracias · por favor" },
  { english: "Gern geschehen · Entschuldigung · Verzeihung · Bitte", pronunciation: "guern gue-shé-en · ent-shúl-di-gung · fer-tsái-ung · bí-te", spanish: "de nada · perdón · disculpe · permiso" },
  { english: "Ja · Nein · Vielleicht · Klar", pronunciation: "ia · nain · fí-láijt · klar", spanish: "sí · no · quizá · claro" },
  { english: "Gut · Sehr gut · Schlecht · Geht so", pronunciation: "gut · zehr gut · shlejt · gueet so", spanish: "bien · muy bien · mal · regular" },
  { english: "Freut mich · Ebenfalls · Willkommen · Willkommen", pronunciation: "froit mij · é-ben-fals · víl-ko-men · víl-ko-men", spanish: "encantado · igualmente · bienvenido · bienvenida" },
  { english: "Herr · Frau · Junge · Mädchen", pronunciation: "jer · frau · yún-gue · mét-jen", spanish: "señor · señora · chico · chica" },
  { english: "Freund · Freundin · Kollege · Kollegin", pronunciation: "froint · froin-din · ko-lé-gue · ko-lé-guin", spanish: "amigo · amiga · compañero · compañera" },
  { english: "Name · Nachname · Person · Leute", pronunciation: "ná-me · náj-na-me · per-zón · lóite", spanish: "nombre · apellido · persona · gente" },
  { english: "oben · unten · rechts · links", pronunciation: "ó-ben · ún-ten · rejs · links", spanish: "arriba · abajo · derecha · izquierda" },
  { english: "vorne · hinten · drinnen · draußen", pronunciation: "fór-ne · jín-ten · drí-nen · dráu-sen", spanish: "delante · detrás · dentro · fuera" },
  { english: "hier · dort · nah · weit", pronunciation: "jir · dort · na · vait", spanish: "aquí · allí · cerca · lejos" },
  { english: "obenauf · unter · gegenüber · rundherum", pronunciation: "ó-ben-auf · ún-ter · gue-gue-nú-ber · runt-je-rum", spanish: "encima · debajo · enfrente · alrededor" },
  { english: "Zentrum · Seite · Ecke · Mitte", pronunciation: "tsén-trum · zái-te · é-ke · mí-te", spanish: "centro · lado · esquina · medio" },
  { english: "Norden · Süden · Osten · Westen", pronunciation: "nór-den · zú-den · ós-ten · vés-ten", spanish: "norte · sur · este · oeste" },
  { english: "Eingang · Ausgang · Tür · Fenster", pronunciation: "áin-gang · áus-gang · tüa · fén-ster", spanish: "entrada · salida · puerta · ventana" },
  { english: "Straße · Weg · Richtung · Ort", pronunciation: "shtrá-se · vek · ríj-tung · ort", spanish: "calle · camino · dirección · lugar" },
  { english: "hochgehen · heruntergehen · hineingehen · hinausgehen", pronunciation: "jój-gue-en · jer-ún-ter-gue-en · ji-náus-gue-en · ji-náus-gue-en", spanish: "subir · bajar · entrar · salir" },
  { english: "geradeaus · zurück · folgen · anhalten", pronunciation: "gue-rá-de-aus · tsu-rük · fól-guen · án-jal-ten", spanish: "recto · volver · seguir · parar" },
  { english: "Wasser · Brot · Ei · Käse", pronunciation: "vás-ser · brot · ai · ké-se", spanish: "agua · pan · huevo · queso" },
  { english: "Milch · Kaffee · Tee · Saft", pronunciation: "milj · ká-fe · te · zaft", spanish: "leche · café · té · zumo" },
  { english: "Fleisch · Fisch · Hähnchen · Reis", pronunciation: "flaish · fish · jén-jen · rais", spanish: "carne · pescado · pollo · arroz" },
  { english: "Nudeln · Kartoffel · Suppe · Salat", pronunciation: "nú-deln · kar-tó-fel · zú-pe · za-lát", spanish: "pasta · patata · sopa · ensalada" },
  { english: "Apfel · Banane · Orange · Zitrone", pronunciation: "áp-fel · ba-ná-ne · o-rán-she · tsi-tró-ne", spanish: "manzana · plátano · naranja · limón" },
  { english: "Tomate · Zwiebel · Karotte · Kopfsalat", pronunciation: "to-má-te · tsví-bel · ka-ró-te · kópf-za-lat", spanish: "tomate · cebolla · zanahoria · lechuga" },
  { english: "Salz · Zucker · Öl · Butter", pronunciation: "zalts · tsú-ker · öl · bú-ter", spanish: "sal · azúcar · aceite · mantequilla" },
  { english: "Frühstück · Mittagessen · Abendessen · Getränk", pronunciation: "frü-shtük · mí-tag-ésen · á-bent-ésen · gue-trénk", spanish: "desayuno · comida · cena · bebida" },
  { english: "Schwein · Rindfleisch · Schinken · Wurst", pronunciation: "shvain · rínt-flaish · shín-ken · vurst", spanish: "cerdo · ternera · jamón · salchicha" },
  { english: "Nachtisch · Obst · Joghurt · Schokolade", pronunciation: "náj-tish · opst · yó-gurt · sho-ko-lá-de", spanish: "postre · fruta · yogur · chocolate" },
  { english: "Haus · Zimmer · Küche · Bad", pronunciation: "jaus · tsím-mer · kú-je · bat", spanish: "casa · habitación · cocina · baño" },
  { english: "Schlafzimmer · Wohnzimmer · Bett · Tisch", pronunciation: "shláf-tsím-mer · vónt-tsím-mer · bet · tish", spanish: "dormitorio · salón · cama · mesa" },
  { english: "Stuhl · Sofa · Schrank · Spiegel", pronunciation: "shtul · zó-fa · shrank · shpí-guel", spanish: "silla · sofá · armario · espejo" },
  { english: "Schlüssel · Telefon · Handy · Ladegerät", pronunciation: "shlú-sel · te-le-fón · jén-di · lá-de-gue-rét", spanish: "llave · teléfono · móvil · cargador" },
  { english: "Tasche · Rucksack · Kleidung · Schuhe", pronunciation: "tá-she · rúk-zak · klái-dung · shú-e", spanish: "bolso · mochila · ropa · zapatos" },
  { english: "Hemd · Hose · Jacke · Mantel", pronunciation: "jemt · jó-ze · yá-ke · mán-tel", spanish: "camisa · pantalón · chaqueta · abrigo" },
  { english: "Handtuch · Seife · Papier · Müll", pronunciation: "jánt-tuj · zái-fe · pa-pír · mül", spanish: "toalla · jabón · papel · basura" },
  { english: "Glas · Tasse · Teller · Löffel", pronunciation: "glas · tá-se · té-ler · ló-fel", spanish: "vaso · taza · plato · cuchara" },
  { english: "Messer · Gabel · Flasche · Kiste", pronunciation: "mé-ser · gá-bel · flá-she · kís-te", spanish: "cuchillo · tenedor · botella · caja" },
  { english: "Tüte · Paket · Uhr · Computer", pronunciation: "tú-te · pa-két · ur · kom-piú-ter", spanish: "bolsa · paquete · reloj · ordenador" },
  { english: "Mann · Frau · Junge · Mädchen", pronunciation: "man · frau · yún-gue · mét-jen", spanish: "hombre · mujer · niño · niña" },
  { english: "Familie · Mutter · Vater · Sohn", pronunciation: "fa-mí-li-e · mú-ter · fá-ter · zon", spanish: "familia · madre · padre · hijo" },
  { english: "Tochter · Bruder · Schwester · Baby", pronunciation: "tój-ter · brú-der · shvés-ter · bé-bi", spanish: "hija · hermano · hermana · bebé" },
  { english: "Kopf · Gesicht · Auge · Mund", pronunciation: "kopf · gue-zíjt · áu-gue · munt", spanish: "cabeza · cara · ojo · boca" },
  { english: "Nase · Ohr · Hand · Arm", pronunciation: "ná-se · or · jant · arm", spanish: "nariz · oído · mano · brazo" },
  { english: "Bein · Fuß · Rücken · Finger", pronunciation: "bain · fus · rü-ken · fín-ger", spanish: "pierna · pie · espalda · dedo" },
  { english: "Arzt · Krankenpfleger · Krankenhaus · Apotheke", pronunciation: "artst · krán-ken-pfle-guer · krán-ken-jaus · a-po-té-ke", spanish: "médico · enfermero · hospital · farmacia" },
  { english: "Schmerz · Fieber · Wunde · Medizin", pronunciation: "shmerts · fí-ber · vún-de · me-di-tsín", spanish: "dolor · fiebre · herida · medicina" },
  { english: "Hunger · Durst · Schlaf · Müdigkeit", pronunciation: "jún-ger · durst · shlaf · mü-dig-kait", spanish: "hambre · sed · sueño · cansancio" },
  { english: "Gesundheit · Krankheit · Hilfe · Notfall", pronunciation: "gue-zúnt-jait · kránk-jait · jíl-fe · nót-fal", spanish: "salud · enfermedad · ayuda · emergencia" },
  { english: "groß · klein · hoch · niedrig", pronunciation: "gros · klain · joj · ní-drig", spanish: "grande · pequeño · alto · bajo" },
  { english: "lang · kurz · breit · eng", pronunciation: "lang · kurts · brait · eng", spanish: "largo · corto · ancho · estrecho" },
  { english: "neu · alt · jung · uralt", pronunciation: "noi · alt · yung · ur-alt", spanish: "nuevo · viejo · joven · antiguo" },
  { english: "gut · schlecht · einfach · schwierig", pronunciation: "gut · shlejt · áin-faj · shví-rig", spanish: "bueno · malo · fácil · difícil" },
  { english: "schnell · langsam · stark · schwach", pronunciation: "shnel · lang-zam · shtark · shvaj", spanish: "rápido · lento · fuerte · débil" },
  { english: "schön · hässlich · sauber · schmutzig", pronunciation: "shön · jés-lij · záu-ber · shmút-tsig", spanish: "bonito · feo · limpio · sucio" },
  { english: "voll · leer · offen · geschlossen", pronunciation: "fol · leer · ó-fen · gue-shló-sen", spanish: "lleno · vacío · abierto · cerrado" },
  { english: "wichtig · nötig · möglich · unmöglich", pronunciation: "víj-tig · nö-tig · möj-lij · un-möj-lij", spanish: "importante · necesario · posible · imposible" },
  { english: "heiß · kalt · trocken · nass", pronunciation: "jais · kalt · tró-ken · nas", spanish: "caliente · frío · seco · mojado" },
  { english: "hell · dunkel · schwer · leicht", pronunciation: "jel · dún-kel · shver · laijt", spanish: "claro · oscuro · pesado · ligero" },
  { english: "heute · morgen · gestern · jetzt", pronunciation: "jói-te · mór-guen · gués-tern · yetst", spanish: "hoy · mañana · ayer · ahora" },
  { english: "später · vorher · bald · spät", pronunciation: "shpé-ter · fór-jer · balt · shpét", spanish: "después · antes · pronto · tarde" },
  { english: "früh · immer · nie · noch", pronunciation: "frü · í-mer · ni · noj", spanish: "temprano · siempre · nunca · todavía" },
  { english: "Montag · Dienstag · Mittwoch · Donnerstag", pronunciation: "món-tag · díns-tag · mít-voj · dó-ners-tag", spanish: "lunes · martes · miércoles · jueves" },
  { english: "Freitag · Samstag · Sonntag · Woche", pronunciation: "frái-tag · zám-stag · zón-tag · vó-je", spanish: "viernes · sábado · domingo · semana" },
  { english: "Januar · Februar · März · April", pronunciation: "yá-nu-ar · fé-bru-ar · merts · a-príl", spanish: "enero · febrero · marzo · abril" },
  { english: "Mai · Juni · Juli · August", pronunciation: "mai · yú-ni · yú-li · au-gúst", spanish: "mayo · junio · julio · agosto" },
  { english: "September · Oktober · November · Dezember", pronunciation: "zep-tém-ber · ok-tó-ber · no-vém-ber · de-tsém-ber", spanish: "septiembre · octubre · noviembre · diciembre" },
  { english: "Datum · Monat · Wochenende · Moment", pronunciation: "dá-tum · mó-nat · vó-jen-en-de · mo-mént", spanish: "fecha · mes · fin de semana · momento" },
  { english: "Stunde · Minute · Sekunde · Jahr", pronunciation: "shtún-de · mi-nú-te · ze-kún-de · iar", spanish: "hora · minuto · segundo · año" },
  { english: "ein Cent · fünf Cent · zehn Cent · zwanzig Cent", pronunciation: "ain tsent · fünf tsent · tsein tsent · tsván-tsig tsent", spanish: "un céntimo · cinco céntimos · diez céntimos · veinte céntimos" },
  { english: "fünfzig Cent · ein Euro · zwei Euro · fünf Euro", pronunciation: "fünf-tsig tsent · ain ói-ro · tsvai ói-ro · fünf ói-ro", spanish: "cincuenta céntimos · un euro · dos euros · cinco euros" },
  { english: "zehn Euro · zwanzig Euro · fünfzig Euro · hundert Euro", pronunciation: "tsein ói-ro · tsván-tsig ói-ro · fünf-tsig ói-ro · hún-dert ói-ro", spanish: "diez euros · veinte euros · cincuenta euros · cien euros" },
  { english: "Münze · Geldschein · Geld · Preis", pronunciation: "mün-tse · guelt-shain · guelt · prais", spanish: "moneda · billete · dinero · precio" },
  { english: "billig · teuer · kostenlos · Rabatt", pronunciation: "bí-lig · tói-er · kós-ten-los · ra-bát", spanish: "barato · caro · gratis · descuento" },
  { english: "bezahlen · kaufen · verkaufen · kosten", pronunciation: "be-tsá-len · káu-fen · fer-káu-fen · kós-ten", spanish: "pagar · comprar · vender · costar" },
  { english: "Karte · Bargeld · Rechnung · Wechselgeld", pronunciation: "kár-te · bár-guelt · réj-nung · vék-sel-guelt", spanish: "tarjeta · efectivo · cuenta · cambio" },
  { english: "Kilo · ein halbes Kilo · Liter · ein halber Liter", pronunciation: "kí-lo · ain jál-bes kí-lo · lí-ter · ain jál-ber lí-ter", spanish: "kilo · medio kilo · litro · medio litro" },
  { english: "viel · wenig · mehr · weniger", pronunciation: "fil · vé-nig · mea · vé-ni-guer", spanish: "mucho · poco · más · menos" },
  { english: "alles · nichts · etwas · genug", pronunciation: "á-les · nijs · ét-vas · gue-nuk", spanish: "todo · nada · algo · suficiente" },
  { english: "sein · sein · haben · machen", pronunciation: "zain · zain · já-ben · má-jen", spanish: "ser · estar · tener · hacer" },
  { english: "gehen · kommen · sehen · schauen", pronunciation: "gué-en · kó-men · zé-en · sháu-en", spanish: "ir · venir · ver · mirar" },
  { english: "sprechen · hören · sagen · fragen", pronunciation: "shpré-jen · jó-ren · zá-guen · frá-guen", spanish: "hablar · escuchar · decir · preguntar" },
  { english: "wissen · verstehen · lernen · lehren", pronunciation: "ví-sen · fer-shté-en · lér-nen · lé-ren", spanish: "saber · entender · aprender · enseñar" },
  { english: "arbeiten · ausruhen · schlafen · aufwachen", pronunciation: "ár-bai-ten · áus-ru-en · shlá-fen · auf-vá-jen", spanish: "trabajar · descansar · dormir · despertar" },
  { english: "essen · trinken · kochen · tragen", pronunciation: "é-sen · trín-ken · kó-jen · trá-guen", spanish: "comer · beber · cocinar · llevar" },
  { english: "wohnen · reisen · fahren · laufen", pronunciation: "vó-nen · rái-sen · fá-ren · láu-fen", spanish: "vivir · viajar · conducir · caminar" },
  { english: "öffnen · schließen · anfangen · beenden", pronunciation: "éf-nen · shlí-sen · án-fang-en · be-én-den", spanish: "abrir · cerrar · empezar · terminar" },
  { english: "warten · helfen · suchen · finden", pronunciation: "vár-ten · jél-fen · zú-jen · fín-den", spanish: "esperar · ayudar · buscar · encontrar" },
  { english: "können · müssen · wollen · brauchen", pronunciation: "kö-nen · müs-en · vó-len · bráu-jen", spanish: "poder · deber · querer · necesitar" },
  { english: "Guten Morgen, ich heiße Carina.", pronunciation: "gú-ten mór-guen, ij jái-se ka-rí-na.", spanish: "Buenos días, me llamo Carina." },
  { english: "Wie heißen Sie?", pronunciation: "vi jái-sen zi?", spanish: "¿Cómo se llama usted?" },
  { english: "Ich heiße Carina.", pronunciation: "ij jái-se ka-rí-na.", spanish: "Me llamo Carina." },
  { english: "Ich komme aus Spanien.", pronunciation: "ij kó-me aus shpá-ni-en.", spanish: "Soy de España." },
  { english: "Ich spreche Spanisch.", pronunciation: "ij shpré-je shpá-nish.", spanish: "Hablo español." },
  { english: "Ich lerne Deutsch.", pronunciation: "ij lér-ne doich.", spanish: "Estoy aprendiendo alemán." },
  { english: "Ich verstehe nicht.", pronunciation: "ij fer-shté-e nijt.", spanish: "No entiendo." },
  { english: "Bitte langsam.", pronunciation: "bí-te lang-zam.", spanish: "Por favor, despacio." },
  { english: "Können Sie das wiederholen?", pronunciation: "kö-nen zi das ví-der-jó-len?", spanish: "¿Puede repetirlo?" },
  { english: "Bis morgen.", pronunciation: "bis mór-guen.", spanish: "Hasta mañana." },
  { english: "Ich möchte Wasser.", pronunciation: "ij möj-te vás-ser.", spanish: "Quiero agua." },
  { english: "Ich möchte Brot.", pronunciation: "ij möj-te brot.", spanish: "Quiero pan." },
  { english: "Ich möchte Kaffee.", pronunciation: "ij möj-te ká-fe.", spanish: "Quiero café." },
  { english: "Ich habe Wasser.", pronunciation: "ij já-be vás-ser.", spanish: "Tengo agua." },
  { english: "Ich habe kein Wasser.", pronunciation: "ij já-be kain vás-ser.", spanish: "No tengo agua." },
  { english: "Ich habe Zeit.", pronunciation: "ij já-be tsait.", spanish: "Tengo tiempo." },
  { english: "Ich habe keine Zeit.", pronunciation: "ij já-be káine tsait.", spanish: "No tengo tiempo." },
  { english: "Ich brauche Wasser.", pronunciation: "ij bráu-je vás-ser.", spanish: "Necesito agua." },
  { english: "Ich brauche Hilfe.", pronunciation: "ij bráu-je jíl-fe.", spanish: "Necesito ayuda." },
  { english: "Danke, alles gut.", pronunciation: "dán-ke, á-les gut.", spanish: "Gracias, está bien." },
  { english: "Wie viel kostet das?", pronunciation: "vi fil kós-tet das?", spanish: "¿Cuánto cuesta esto?" },
  { english: "Das kostet fünf Euro.", pronunciation: "das kós-tet fünf ói-ro.", spanish: "Esto cuesta cinco euros." },
  { english: "Ich möchte dieses Brot.", pronunciation: "ij möj-te dí-ses brot.", spanish: "Quiero este pan." },
  { english: "Ich möchte zwei Eier.", pronunciation: "ij möj-te tsvai ái-er.", spanish: "Quiero dos huevos." },
  { english: "Ich nehme das.", pronunciation: "ij né-me das.", spanish: "Me llevo esto." },
  { english: "Noch eine Flasche Wasser, bitte.", pronunciation: "noj ái-ne flá-she vás-ser, bí-te.", spanish: "Otra botella de agua, por favor." },
  { english: "Eine Tüte, bitte.", pronunciation: "ái-ne tú-te, bí-te.", spanish: "Una bolsa, por favor." },
  { english: "Kann ich mit Karte bezahlen?", pronunciation: "kan ij mit kár-te be-tsá-len?", spanish: "¿Puedo pagar con tarjeta?" },
  { english: "Bar oder mit Karte?", pronunciation: "bar ó-der mit kár-te?", spanish: "¿En efectivo o con tarjeta?" },
  { english: "Vielen Dank.", pronunciation: "fí-len dank.", spanish: "Muchas gracias." },
  { english: "Ich bin müde.", pronunciation: "ij bin mü-de.", spanish: "Estoy cansada." },
  { english: "Ich habe Hunger.", pronunciation: "ij já-be jún-ger.", spanish: "Tengo hambre." },
  { english: "Ich habe Durst.", pronunciation: "ij já-be durst.", spanish: "Tengo sed." },
  { english: "Mir ist kalt.", pronunciation: "mir ist kalt.", spanish: "Tengo frío." },
  { english: "Mir ist heiß.", pronunciation: "mir ist jais.", spanish: "Tengo calor." },
  { english: "Ich brauche eine Pause.", pronunciation: "ij bráu-je ái-ne páu-ze.", spanish: "Necesito un descanso." },
  { english: "Ich brauche Hilfe.", pronunciation: "ij bráu-je jíl-fe.", spanish: "Necesito ayuda." },
  { english: "Ich bin fertig.", pronunciation: "ij bin fér-tig.", spanish: "He terminado." },
  { english: "Ich bin bereit.", pronunciation: "ij bin be-ráit.", spanish: "Estoy lista." },
  { english: "Alles ist gut.", pronunciation: "á-les ist gut.", spanish: "Todo está bien." },
  { english: "Wo ist die Toilette?", pronunciation: "vo ist di to-a-lé-te?", spanish: "¿Dónde está el baño?" },
  { english: "Wo ist der Bahnhof?", pronunciation: "vo ist dea bán-jof?", spanish: "¿Dónde está la estación?" },
  { english: "Wo ist das Hotel?", pronunciation: "vo ist das jo-tél?", spanish: "¿Dónde está el hotel?" },
  { english: "Ich bin hier.", pronunciation: "ij bin jir.", spanish: "Estoy aquí." },
  { english: "Es ist dort.", pronunciation: "es ist dort.", spanish: "Está allí." },
  { english: "Hier ist der Eingang.", pronunciation: "jir ist dea áin-gang.", spanish: "Aquí está la entrada." },
  { english: "Dort ist der Ausgang.", pronunciation: "dort ist dea áus-gang.", spanish: "Allí está la salida." },
  { english: "Nach links, bitte.", pronunciation: "naj links, bí-te.", spanish: "A la izquierda, por favor." },
  { english: "Nach rechts, bitte.", pronunciation: "naj rejs, bí-te.", spanish: "A la derecha, por favor." },
  { english: "Geradeaus.", pronunciation: "gue-rá-de-aus.", spanish: "Todo recto." },
  { english: "Ich gehe nach Hause.", pronunciation: "ij gue-e naj jáu-ze.", spanish: "Voy a casa." },
  { english: "Ich gehe zur Arbeit.", pronunciation: "ij gue-e tsur ár-bait.", spanish: "Voy al trabajo." },
  { english: "Ich komme morgen.", pronunciation: "ij kó-me mór-guen.", spanish: "Vengo mañana." },
  { english: "Ich komme später.", pronunciation: "ij kó-me shpé-ter.", spanish: "Vengo más tarde." },
  { english: "Ich fahre nach Köln.", pronunciation: "ij fá-re naj köln.", spanish: "Voy a Colonia." },
  { english: "Ich gehe zu Fuß.", pronunciation: "ij gue-e tsu fus.", spanish: "Voy a pie." },
  { english: "Warten Sie, bitte.", pronunciation: "vár-ten zi, bí-te.", spanish: "Espere, por favor." },
  { english: "Kommen Sie, bitte.", pronunciation: "kó-men zi, bí-te.", spanish: "Venga, por favor." },
  { english: "Gehen Sie geradeaus.", pronunciation: "gué-en zi gue-rá-de-aus.", spanish: "Siga recto." },
  { english: "Kommen Sie hierher, bitte.", pronunciation: "kó-men zi jir-jéa, bí-te.", spanish: "Venga aquí, por favor." },
  { english: "Ich arbeite heute.", pronunciation: "ij ár-bai-te jói-te.", spanish: "Trabajo hoy." },
  { english: "Ich arbeite morgen.", pronunciation: "ij ár-bai-te mór-guen.", spanish: "Trabajo mañana." },
  { english: "Ich arbeite heute nicht.", pronunciation: "ij ár-bai-te jói-te nijt.", spanish: "No trabajo hoy." },
  { english: "Gestern habe ich nicht gearbeitet.", pronunciation: "gués-tern já-be ij nijt gue-ár-bai-tet.", spanish: "Ayer no trabajé." },
  { english: "Am Sonntag habe ich frei.", pronunciation: "am zón-tag já-be ij frai.", spanish: "El domingo tengo libre." },
  { english: "Ich bin bei der Arbeit.", pronunciation: "ij bin bai dea ár-bait.", spanish: "Estoy en el trabajo." },
  { english: "Wo ist mein Arbeitsplatz?", pronunciation: "vo ist main ár-baits-plats?", spanish: "¿Dónde está mi puesto de trabajo?" },
  { english: "Ich brauche eine Pause.", pronunciation: "ij bráu-je ái-ne páu-ze.", spanish: "Necesito un descanso." },
  { english: "Ich bin fertig.", pronunciation: "ij bin fér-tig.", spanish: "He terminado." },
  { english: "Bis morgen bei der Arbeit.", pronunciation: "bis mór-guen bai dea ár-bait.", spanish: "Hasta mañana en el trabajo." },
  { english: "Hier ist mein Reisepass.", pronunciation: "jir ist main ráize-pas.", spanish: "Aquí está mi pasaporte." },
  { english: "Hier ist mein Personalausweis.", pronunciation: "jir ist main per-zo-nal-áus-vais.", spanish: "Aquí está mi documento de identidad." },
  { english: "Hier sind meine Dokumente.", pronunciation: "jir zint mái-ne do-ku-mén-te.", spanish: "Aquí están mis documentos." },
  { english: "Einen Moment, bitte.", pronunciation: "ái-nen mo-mént, bí-te.", spanish: "Un momento, por favor." },
  { english: "Ich verstehe die Frage nicht.", pronunciation: "ij fer-shté-e di frá-gue nijt.", spanish: "No entiendo la pregunta." },
  { english: "Bitte sprechen Sie langsam.", pronunciation: "bí-te shpré-jen zi lang-zam.", spanish: "Por favor, hable despacio." },
  { english: "Können Sie mir helfen?", pronunciation: "kö-nen zi mir jél-fen?", spanish: "¿Puede ayudarme?" },
  { english: "Ich brauche Hilfe.", pronunciation: "ij bráu-je jíl-fe.", spanish: "Necesito ayuda." },
  { english: "Kein Problem.", pronunciation: "kain pro-blém.", spanish: "No hay problema." },
  { english: "Danke für Ihre Hilfe.", pronunciation: "dán-ke für í-re jíl-fe.", spanish: "Gracias por su ayuda." },
  { english: "Ja, klar.", pronunciation: "ia, klar.", spanish: "Sí, claro." },
  { english: "Nein, leider nicht.", pronunciation: "nain, lái-der nijt.", spanish: "No, lamentablemente no." },
  { english: "Ich weiß es nicht.", pronunciation: "ij vais es nijt.", spanish: "No lo sé." },
  { english: "Ich verstehe.", pronunciation: "ij fer-shté-e.", spanish: "Entiendo." },
  { english: "Ich verstehe nicht.", pronunciation: "ij fer-shté-e nijt.", spanish: "No entiendo." },
  { english: "Noch einmal, bitte.", pronunciation: "noj áin-mal, bí-te.", spanish: "Otra vez, por favor." },
  { english: "Was bedeutet das?", pronunciation: "vas be-dói-tet das?", spanish: "¿Qué significa eso?" },
  { english: "Wie sagt man das auf Deutsch?", pronunciation: "vi zakt man das auf doich?", spanish: "¿Cómo se dice eso en alemán?" },
  { english: "Können Sie das schreiben?", pronunciation: "kö-nen zi das shrái-ben?", spanish: "¿Puede escribirlo?" },
  { english: "Jetzt verstehe ich.", pronunciation: "yetst fer-shté-e ij.", spanish: "Ahora entiendo." },
  { english: "Morgen arbeite ich.", pronunciation: "mór-guen ár-bai-te ij.", spanish: "Mañana trabajo." },
  { english: "Morgen fahre ich nach Köln.", pronunciation: "mór-guen fá-re ij naj köln.", spanish: "Mañana voy a Colonia." },
  { english: "Morgen habe ich frei.", pronunciation: "mór-guen já-be ij frai.", spanish: "Mañana tengo libre." },
  { english: "Gestern habe ich gearbeitet.", pronunciation: "gués-tern já-be ij gue-ár-bai-tet.", spanish: "Ayer trabajé." },
  { english: "Gestern war ich zu Hause.", pronunciation: "gués-tern var ij tsu jáu-ze.", spanish: "Ayer estuve en casa." },
  { english: "Heute arbeite ich.", pronunciation: "jói-te ár-bai-te ij.", spanish: "Hoy trabajo." },
  { english: "Heute bin ich hier.", pronunciation: "jói-te bin ij jir.", spanish: "Hoy estoy aquí." },
  { english: "Am Sonntag reise ich.", pronunciation: "am zón-tag rái-ze ij.", spanish: "El domingo viajo." },
  { english: "Bis morgen.", pronunciation: "bis mór-guen.", spanish: "Hasta mañana." },
  { english: "Bis Sonntag.", pronunciation: "bis zón-tag.", spanish: "Hasta el domingo." },
  { english: "Guten Morgen!", pronunciation: "gú-ten mór-guen!", spanish: "¡Buenos días!" },
  { english: "Guten Morgen! Wie heißen Sie?", pronunciation: "gú-ten mór-guen! vi jái-sen zi?", spanish: "¡Buenos días! ¿Cómo se llama?" },
  { english: "Ich heiße Carina.", pronunciation: "ij jái-se ka-rí-na.", spanish: "Me llamo Carina." },
  { english: "Woher kommen Sie?", pronunciation: "vo-jéa kó-men zi?", spanish: "¿De dónde viene?" },
  { english: "Ich komme aus Spanien.", pronunciation: "ij kó-me aus shpá-ni-en.", spanish: "Vengo de España." },
  { english: "Sprechen Sie Deutsch?", pronunciation: "shpré-jen zi doich?", spanish: "¿Habla alemán?" },
  { english: "Ich lerne Deutsch.", pronunciation: "ij lér-ne doich.", spanish: "Estoy aprendiendo alemán." },
  { english: "Sprechen Sie Englisch?", pronunciation: "shpré-jen zi éng-lish?", spanish: "¿Habla inglés?" },
  { english: "Ein bisschen.", pronunciation: "ain bís-jen.", spanish: "Un poco." },
  { english: "Bis später!", pronunciation: "bis shpé-ter!", spanish: "¡Hasta luego!" },
  { english: "Guten Morgen!", pronunciation: "gú-ten mór-guen!", spanish: "¡Buenos días!" },
  { english: "Guten Tag!", pronunciation: "gú-ten tak!", spanish: "¡Buenas tardes!" },
  { english: "Können Sie hier unterschreiben?", pronunciation: "kö-nen zi jir ún-ter-shrái-ben?", spanish: "¿Puede firmar aquí?" },
  { english: "Bitte unterschreiben Sie hier.", pronunciation: "bí-te ún-ter-shrái-ben zi jir.", spanish: "Por favor, firme aquí." },
  { english: "Einen Moment, bitte.", pronunciation: "ái-nen mo-mént, bí-te.", spanish: "Un momento, por favor." },
  { english: "Ist das Ihr Name?", pronunciation: "ist das ia ná-me?", spanish: "¿Ese es su nombre?" },
  { english: "Ja, das ist mein Name.", pronunciation: "ia, das ist main ná-me.", spanish: "Sí, ese es mi nombre." },
  { english: "Danke.", pronunciation: "dán-ke.", spanish: "Gracias." },
  { english: "Alles ist klar.", pronunciation: "á-les ist klar.", spanish: "Todo está claro." },
  { english: "Ich wünsche Ihnen einen schönen Tag!", pronunciation: "ij vün-she í-nen ái-nen shö-nen tak!", spanish: "¡Que tenga un buen día!" },
  { english: "Was möchten Sie?", pronunciation: "vas möj-ten zi?", spanish: "¿Qué desea?" },
  { english: "Ich möchte Wasser.", pronunciation: "ij möj-te vás-ser.", spanish: "Quiero agua." },
  { english: "Möchten Sie Brot?", pronunciation: "möj-ten zi brot?", spanish: "¿Quiere pan?" },
  { english: "Ja, bitte.", pronunciation: "ia, bí-te.", spanish: "Sí, por favor." },
  { english: "Nein, danke.", pronunciation: "nain, dán-ke.", spanish: "No, gracias." },
  { english: "Das oder das?", pronunciation: "das ó-der das?", spanish: "¿Esto o esto?" },
  { english: "Das, bitte.", pronunciation: "das, bí-te.", spanish: "Esto, por favor." },
  { english: "Hier oder dort?", pronunciation: "jir ó-der dort?", spanish: "¿Aquí o allí?" },
  { english: "Hier, bitte.", pronunciation: "jir, bí-te.", spanish: "Aquí, por favor." },
  { english: "Vielen Dank.", pronunciation: "fí-len dank.", spanish: "Muchas gracias." },
  { english: "Entschuldigung, wo ist der Bahnhof?", pronunciation: "ent-shúl-di-gung, vo ist dea bán-jof?", spanish: "Disculpe, ¿dónde está la estación?" },
  { english: "Gehen Sie geradeaus.", pronunciation: "gué-en zi gue-rá-de-aus.", spanish: "Siga recto." },
  { english: "Dann nach rechts.", pronunciation: "dan naj rejs.", spanish: "Después, a la derecha." },
  { english: "Danke für Ihre Hilfe.", pronunciation: "dán-ke für í-re jíl-fe.", spanish: "Gracias por su ayuda." },
  { english: "Entschuldigung, ich verstehe nicht.", pronunciation: "ent-shúl-di-gung, ij fer-shté-e nijt.", spanish: "Disculpe, no entiendo." },
  { english: "Bitte langsam.", pronunciation: "bí-te lang-zam.", spanish: "Por favor, despacio." },
  { english: "Noch einmal, bitte.", pronunciation: "noj áin-mal, bí-te.", spanish: "Otra vez, por favor." },
  { english: "Jetzt verstehe ich.", pronunciation: "yetst fer-shté-e ij.", spanish: "Ahora entiendo." },
  { english: "Kein Problem.", pronunciation: "kain pro-blém.", spanish: "No hay problema." },
  { english: "Vielen Dank.", pronunciation: "fí-len dank.", spanish: "Muchas gracias." },
  { english: "Guten Morgen, ich heiße Carina.", pronunciation: "gú-ten mór-guen, ij jái-se ka-rí-na.", spanish: "Buenos días, me llamo Carina." },
  { english: "Ich komme aus Spanien.", pronunciation: "ij kó-me aus shpá-ni-en.", spanish: "Vengo de España." },
  { english: "Ich lerne Deutsch.", pronunciation: "ij lér-ne doich.", spanish: "Estoy aprendiendo alemán." },
  { english: "Ich verstehe nicht.", pronunciation: "ij fer-shté-e nijt.", spanish: "No entiendo." },
  { english: "Bitte sprechen Sie langsam.", pronunciation: "bí-te shpré-jen zi lang-zam.", spanish: "Por favor, hable despacio." },
  { english: "Ich möchte Wasser, bitte.", pronunciation: "ij möj-te vás-ser, bí-te.", spanish: "Quiero agua, por favor." },
  { english: "Wo ist die Toilette?", pronunciation: "vo ist di to-a-lé-te?", spanish: "¿Dónde está el baño?" },
  { english: "Können Sie mir helfen?", pronunciation: "kö-nen zi mir jél-fen?", spanish: "¿Puede ayudarme?" },
  { english: "Vielen Dank. Bis morgen.", pronunciation: "fí-len dank. bis mór-guen.", spanish: "Muchas gracias. Hasta mañana." },
  { english: "Gute Nacht.", pronunciation: "gú-te najt.", spanish: "Buenas noches." }
];
